spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: turbopremioss@gmail.com
    password: dcem rvjx trrc ufub
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/turbo_premios
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false

logging:
  level:
    com.turbopremios: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.transaction: TRACE
    org.springframework.orm.jpa: DEBUG

mercadopago:
  access-token: APP_USR-5510449896558649-060114-76080479986f8ed33551b5688bd31f3b-3432219360

asaas:
  api-url: https://api-sandbox.asaas.com/v3
  api-key: $aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjljYzAyNDUxLTM4ZmYtNGU2Ny1hN2Q1LTMyMmQ4NDQxNzA4Mzo6JGFhY2hfZGJlNjc2MzMtMWY0NS00OGJkLTk3ZjMtMWU1MGY0NDUxNWRj
  webhook-token: whsec_5W_PyvYFN_Yle8TzmAgwigJbsGvG0DUMEcxYS5lTCs0

app:
  pix:
    gateway: asaas